#!/usr/bin/env bash
# ============================================================================
# 999 PRO — generate-env.sh
# v25.0-audit-fix: ONE-COMMAND bootstrap for production deployment.
#
# Generates:
#   1. .env.prod       — all required env vars with fresh random secrets
#   2. secrets/postgres_password.txt — Docker file-based secret for postgres
#   3. (optional) prints a summary you can paste into your password manager
#
# Usage:
#   ./generate-env.sh                       # generates .env.prod + secrets
#   ./generate-env.sh --stdout              # prints env to stdout (no files)
#   ./generate-env.sh --domain example.com  # override default domain
#   ./generate-env.sh --help                # show this help
#
# After generation:
#   1. Edit .env.prod (set SMTP_*, APPLE_TEAM_ID, YANDEX key, etc.)
#   2. docker compose -f docker-compose.prod.yml --env-file .env.prod up -d --build
#
# Idempotent: re-running overwrites .env.prod and rotates ALL secrets.
# ============================================================================

set -euo pipefail

# ---------- defaults ----------
DOMAIN="${APP_DOMAIN:-999.pro}"
STDOUT_ONLY=0

# ---------- arg parsing ----------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --stdout) STDOUT_ONLY=1; shift ;;
    --domain) DOMAIN="$2"; shift 2 ;;
    --help|-h)
      sed -n '2,28p' "$0"
      exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

# ---------- helpers ----------
rand_hex() { openssl rand -hex "${1:-32}"; }
rand_base64url() { openssl rand -base64 32 | tr '+/' '-_' | tr -d '='; }

# VAPID keys need to be valid P-256 ECDSA key pair in base64url.
# Use Node.js crypto (ECDH on prime256v1) — produces correct raw key bytes
# that web-push expects. We can't rely on `bunx web-push generate-vapid-keys`
# because web-push is only in backend's deps (not project root).
gen_vapid_keys() {
  node -e '
    const crypto = require("crypto");
    const ecdh = crypto.createECDH("prime256v1");
    ecdh.generateKeys();
    const publicKey  = ecdh.getPublicKey().toString("base64url");
    const privateKey = ecdh.getPrivateKey().toString("base64url");
    console.log("PUB=" + publicKey);
    console.log("PRIV=" + privateKey);
  '
}

# ---------- generate secrets ----------
JWT_SECRET="$(rand_hex 48)"
FIRST_RUN_TOKEN="$(rand_hex 32)"
RESET_ADMIN_TOKEN="$(rand_hex 32)"
IP_HASH_PEPPER="$(rand_hex 32)"
POSTGRES_PASSWORD="$(rand_hex 24)"

# Parse VAPID keypair from gen_vapid_keys output (PUB=... / PRIV=...)
VAPID_OUTPUT="$(gen_vapid_keys)"
VAPID_PUBLIC_KEY="$(printf '%s\n' "$VAPID_OUTPUT" | grep '^PUB='  | cut -d= -f2-)"
VAPID_PRIVATE_KEY="$(printf '%s\n' "$VAPID_OUTPUT" | grep '^PRIV=' | cut -d= -f2-)"

# ---------- compose env content ----------
read -r -d '' ENV_CONTENT <<EOF || true
# ============================================================================
# 999 PRO — production .env.prod (auto-generated by ./generate-env.sh)
# Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Domain:    ${DOMAIN}
# ============================================================================
# This file is consumed by:
#   docker compose -f docker-compose.prod.yml --env-file .env.prod up -d --build
# All \${VAR:?error} variables in docker-compose.prod.yml MUST be set here.
# ============================================================================

# ---- Domain (Caddy will request Let's Encrypt cert for this domain) ----
APP_DOMAIN=${DOMAIN}
APP_PUBLIC_URL=https://${DOMAIN}

# ---- Database (Postgres) ----
# Password is also written to ./secrets/postgres_password.txt — keep both in
# sync if you change one. The compose file reads the password from the secret
# file (NOT from this env var) for the Postgres container.
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ---- Auth secrets (auto-generated, do NOT reuse in another env) ----
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=7d
FIRST_RUN_TOKEN=${FIRST_RUN_TOKEN}
RESET_ADMIN_TOKEN=${RESET_ADMIN_TOKEN}

# ---- Security peppers ----
IP_HASH_PEPPER=${IP_HASH_PEPPER}

# ---- Web Push (VAPID) — auto-generated P-256 keypair ----
# WARNING: rotating VAPID keys invalidates ALL existing push subscriptions.
VAPID_SUBJECT=mailto:admin@${DOMAIN}
VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}

# ---- Email verification ----
EMAIL_VERIFICATION_REQUIRED=true

# ---- SMTP (REQUIRED if EMAIL_VERIFICATION_REQUIRED=true) ----
# Fill these in before deploying. Supports Yandex/Gmail/Mailgun/SendGrid/SES.
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=no-reply@${DOMAIN}
SMTP_SECURE=false

# ---- CORS (auto-derived from APP_DOMAIN) ----
CLIENT_ORIGIN=https://${DOMAIN},https://studio.${DOMAIN}

# ---- Yandex Maps (optional — required for delivery map on non-localhost) ----
NEXT_PUBLIC_YANDEX_MAPS_API_KEY=

# ---- Mobile deep linking (optional — required for native app integration) ----
APPLE_TEAM_ID=
APPLE_BUNDLE_ID=pro.ninehundred.app
ANDROID_PACKAGE_NAME=pro.ninehundred.app
ANDROID_SHA256_FINGERPRINT=

# ---- AI Assistant (optional — DeepSeek) ----
DEEPSEEK_API_KEY=
DEEPSEEK_API_BASE=https://api.deepseek.com
DEEPSEEK_MODEL=deepseek-chat

# ---- Sentry (optional) ----
# SENTRY_DSN=
# SENTRY_SEND_PII=false

# ---- TURN server (optional — needed for WebRTC calls behind symmetric NAT) ----
# TURN_URL=
# TURN_USERNAME=
# TURN_CREDENTIAL=
EOF

# ---------- emit / write ----------
if [[ "$STDOUT_ONLY" == "1" ]]; then
  echo "$ENV_CONTENT"
  exit 0
fi

# Resolve script directory (works from any CWD)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${SCRIPT_DIR}"
ENV_FILE="${PROJECT_DIR}/.env.prod"
SECRETS_DIR="${PROJECT_DIR}/secrets"
SECRETS_FILE="${SECRETS_DIR}/postgres_password.txt"

# Write .env.prod
echo "$ENV_CONTENT" > "$ENV_FILE"
chmod 600 "$ENV_FILE"

# Write Docker secret
mkdir -p "$SECRETS_DIR"
echo -n "$POSTGRES_PASSWORD" > "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"

cat <<SUMMARY

==============================================================================
✅ Generated successfully
==============================================================================

  .env.prod                          → ${ENV_FILE}
  secrets/postgres_password.txt      → ${SECRETS_FILE}

NEXT STEPS:
  1. Edit ${ENV_FILE} and fill in:
       SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS  (required for email verify)
       NEXT_PUBLIC_YANDEX_MAPS_API_KEY             (optional)
       APPLE_TEAM_ID, ANDROID_SHA256_FINGERPRINT   (optional, mobile deep links)
       DEEPSEEK_API_KEY                            (optional, AI assistant)

  2. Make sure DNS A record for ${DOMAIN} (and studio.${DOMAIN}) points to
     this server's public IP — Caddy needs this for Let's Encrypt TLS.

  3. Build & start:
       docker compose -f docker-compose.prod.yml --env-file .env.prod up -d --build

  4. Check status:
       docker compose -f docker-compose.prod.yml ps
       docker compose -f docker-compose.prod.yml logs -f backend

  5. Create first admin (after backend is healthy):
       curl -X POST https://${DOMAIN}/api/auth/first-run \\
         -H "Content-Type: application/json" \\
         -H "X-Setup-Admin-Token: ${FIRST_RUN_TOKEN}" \\
         -d '{"username":"admin","email":"admin@${DOMAIN}","password":"YOUR_STRONG_PASSWORD"}'

==============================================================================
SUMMARY
