// ============================================================================
// 999 PRO — setup.js
// ----------------------------------------------------------------------------
// One-time setup: generates .env files with cryptographically-strong secrets
// for the backend, frontend (root), and studio.
//
// Run: `npm run setup` (or `node scripts/setup.js`)
//
// Idempotent: if .env files already exist, they will NOT be overwritten.
// Pass --force to regenerate (WARNING: rotates all secrets — existing JWTs
// become invalid, push subscriptions break, etc.).
// ============================================================================

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const ROOT = path.resolve(__dirname, '..');
const BACKEND = path.join(ROOT, 'mini-services', 'backend');
const STUDIO = path.join(ROOT, 'mini-services', 'studio');

const args = process.argv.slice(2);
const FORCE = args.includes('--force') || args.includes('-f');

// ---------- helpers ----------
function randHex(bytes) {
  return crypto.randomBytes(bytes).toString('hex');
}

function genVapidKeys() {
  // P-256 ECDSA keypair, raw bytes encoded as base64url — what web-push expects.
  const ecdh = crypto.createECDH('prime256v1');
  ecdh.generateKeys();
  return {
    publicKey: ecdh.getPublicKey().toString('base64url'),
    privateKey: ecdh.getPrivateKey().toString('base64url'),
  };
}

function writeIfMissing(filePath, content, label) {
  if (fs.existsSync(filePath) && !FORCE) {
    console.log(`  ✓ ${label}: ${path.relative(ROOT, filePath)} (already exists — skipped)`);
    return false;
  }
  fs.writeFileSync(filePath, content, { mode: 0o600 });
  console.log(`  ✓ ${label}: ${path.relative(ROOT, filePath)} (${FORCE ? 'regenerated' : 'created'})`);
  return true;
}

// ---------- generate secrets ----------
console.log('\n🔐 Generating secrets...');

const JWT_SECRET = randHex(48);
const FIRST_RUN_TOKEN = randHex(32);
const RESET_ADMIN_TOKEN = randHex(32);
const IP_HASH_PEPPER = randHex(32);
const vapid = genVapidKeys();

// ---------- detect domain ----------
const DEFAULT_DOMAIN = process.env.APP_DOMAIN || 'localhost';
const APP_PUBLIC_URL = process.env.APP_PUBLIC_URL || (DEFAULT_DOMAIN === 'localhost'
  ? 'http://localhost:3000'
  : `https://${DEFAULT_DOMAIN}`);

// ---------- backend .env ----------
console.log('\n📝 Writing .env files...');

const backendEnv = `# 999 PRO Backend — .env (auto-generated by scripts/setup.js)
# Generated: ${new Date().toISOString()}
# Edit values below as needed. NEVER commit this file.

# ---- Runtime ----
NODE_ENV=production
PORT=4000

# ---- Database ----
# SQLite (default — single file, no separate DB server needed).
# For PostgreSQL, replace with: postgresql://user:password@host:5432/dbname?schema=public
BACKEND_DATABASE_URL="file:./dev.db"

# ---- CORS ----
# Comma-separated list of allowed origins. For production with a domain:
#   CLIENT_ORIGIN="https://YOUR_DOMAIN,https://studio.YOUR_DOMAIN"
CLIENT_ORIGIN="http://localhost:3000,http://localhost:3001"

# ---- Trust proxy (set to "true" if behind Nginx/Caddy/Cloudflare) ----
TRUST_PROXY=false

# ---- Auth secrets (auto-generated) ----
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=7d
FIRST_RUN_TOKEN=${FIRST_RUN_TOKEN}
RESET_ADMIN_TOKEN=${RESET_ADMIN_TOKEN}
IP_HASH_PEPPER=${IP_HASH_PEPPER}

# ---- Bcrypt rounds ----
BCRYPT_ROUNDS=12

# ---- Web Push (VAPID) — auto-generated P-256 keypair ----
VAPID_SUBJECT=mailto:admin@${DEFAULT_DOMAIN}
VAPID_PUBLIC_KEY=${vapid.publicKey}
VAPID_PRIVATE_KEY=${vapid.privateKey}

# ---- Email verification ----
EMAIL_VERIFICATION_REQUIRED=false

# ---- SMTP (required if EMAIL_VERIFICATION_REQUIRED=true) ----
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=no-reply@${DEFAULT_DOMAIN}
SMTP_SECURE=false

# ---- Admin / seed ----
BYPASS_ADMIN_TOTP=false
SEED_USER_PASSWORD=demo12345
ADMIN_EMAIL=admin@${DEFAULT_DOMAIN}
ADMIN_USERNAME=admin

# ---- Public URL ----
APP_PUBLIC_URL=${APP_PUBLIC_URL}

# ---- AI Assistant (optional) ----
DEEPSEEK_API_KEY=
DEEPSEEK_API_BASE=https://api.deepseek.com
DEEPSEEK_MODEL=deepseek-chat
`;

const frontendEnv = `# 999 PRO Frontend — .env (auto-generated by scripts/setup.js)
# Edit values below as needed. NEVER commit this file.

# ---- Backend URL ----
# In production with Nginx: http://localhost:4000 (server-side)
BACKEND_URL=http://localhost:4000

# ---- Public API base ----
# Empty = use relative /api/* paths (recommended when behind Nginx reverse proxy)
NEXT_PUBLIC_API_BASE=

# ---- Yandex Maps API key (optional) ----
NEXT_PUBLIC_YANDEX_MAPS_API_KEY=

# ---- Iframe embedding (false in prod for clickjacking protection) ----
ALLOW_IFRAME=false

# ---- AI Assistant (optional, server-side only) ----
DEEPSEEK_API_KEY=
DEEPSEEK_API_BASE=https://api.deepseek.com
DEEPSEEK_MODEL=deepseek-chat

# ---- Mobile deep linking (optional) ----
APPLE_TEAM_ID=
APPLE_BUNDLE_ID=pro.ninehundred.app
ANDROID_PACKAGE_NAME=pro.ninehundred.app
ANDROID_SHA256_FINGERPRINT=
`;

const studioEnv = `# 999 PRO Studio — .env (auto-generated by scripts/setup.js)
# Edit values below as needed. NEVER commit this file.

# ---- API base URL ----
NEXT_PUBLIC_API_BASE=

# ---- Public app URL ----
NEXT_PUBLIC_APP_URL=${APP_PUBLIC_URL}

# ---- Backend origin (server-side proxy) ----
NEXT_PUBLIC_BACKEND_ORIGIN=http://localhost:4000

# ---- Yandex Maps API key (optional) ----
NEXT_PUBLIC_YANDEX_MAPS_API_KEY=

# ---- Iframe embedding (true so the main app can embed /studio) ----
ALLOW_IFRAME=true
`;

writeIfMissing(path.join(BACKEND, '.env'), backendEnv, 'backend .env');
writeIfMissing(path.join(ROOT, '.env'), frontendEnv, 'frontend .env');
writeIfMissing(path.join(STUDIO, '.env'), studioEnv, 'studio .env');

// ---------- summary ----------
console.log('\n' + '='.repeat(80));
console.log('✅ Setup complete');
console.log('='.repeat(80));
console.log(`
Generated files:
  .env                            (frontend)
  mini-services/backend/.env      (backend)
  mini-services/studio/.env       (studio)

NEXT STEPS:
  1. Review and edit .env files (SMTP, domain, Yandex key, etc.)
     Especially set these in mini-services/backend/.env if you have a domain:
       CLIENT_ORIGIN=https://YOUR_DOMAIN,https://studio.YOUR_DOMAIN
       APP_PUBLIC_URL=https://YOUR_DOMAIN
       SMTP_HOST / SMTP_PORT / SMTP_USER / SMTP_PASS  (if email verify on)

  2. Build the project:
       npm run build

  3. Start all services:
       npm run start

  4. Create first admin (after backend is up on port 4000):
       curl -X POST http://localhost:4000/api/auth/first-run \\
         -H "Content-Type: application/json" \\
         -H "X-Setup-Admin-Token: ${FIRST_RUN_TOKEN}" \\
         -d '{"username":"admin","email":"admin@example.com","password":"YOUR_PASSWORD"}'

  5. Open the app:
       Frontend: http://localhost:3000
       Studio:   http://localhost:3001/studio
       Backend:  http://localhost:4000/api/health

To regenerate secrets later (rotates ALL secrets — existing sessions break):
  npm run setup -- --force
`);
