// v25.23 — Страны мира: ISO-коды для флагов (public/flags/4x3/{code}.svg),
// русские названия и столицы. Используется в «Угадай флаг» и «Угадай столицу».

export interface Country {
  code: string // ISO 3166-1 alpha-2 в НИЖНЕМ регистре, напр. 'ru'
  name: string // русское название страны
  capital: string // русское название столицы
}

export const COUNTRIES: Country[] = [
  // ── Европа ────────────────────────────────────────────────────
  { code: 'ru', name: 'Россия', capital: 'Москва' },
  { code: 'ua', name: 'Украина', capital: 'Киев' },
  { code: 'by', name: 'Беларусь', capital: 'Минск' },
  { code: 'pl', name: 'Польша', capital: 'Варшава' },
  { code: 'de', name: 'Германия', capital: 'Берлин' },
  { code: 'fr', name: 'Франция', capital: 'Париж' },
  { code: 'gb', name: 'Великобритания', capital: 'Лондон' },
  { code: 'it', name: 'Италия', capital: 'Рим' },
  { code: 'es', name: 'Испания', capital: 'Мадрид' },
  { code: 'pt', name: 'Португалия', capital: 'Лиссабон' },
  { code: 'nl', name: 'Нидерланды', capital: 'Амстердам' },
  { code: 'be', name: 'Бельгия', capital: 'Брюссель' },
  { code: 'lu', name: 'Люксембург', capital: 'Люксембург' },
  { code: 'ch', name: 'Швейцария', capital: 'Берн' },
  { code: 'at', name: 'Австрия', capital: 'Вена' },
  { code: 'cz', name: 'Чехия', capital: 'Прага' },
  { code: 'sk', name: 'Словакия', capital: 'Братислава' },
  { code: 'hu', name: 'Венгрия', capital: 'Будапешт' },
  { code: 'ro', name: 'Румыния', capital: 'Бухарест' },
  { code: 'bg', name: 'Болгария', capital: 'София' },
  { code: 'gr', name: 'Греция', capital: 'Афины' },
  { code: 'al', name: 'Албания', capital: 'Тирана' },
  { code: 'mk', name: 'Северная Македония', capital: 'Скопье' },
  { code: 'rs', name: 'Сербия', capital: 'Белград' },
  { code: 'me', name: 'Черногория', capital: 'Подгорица' },
  { code: 'ba', name: 'Босния и Герцеговина', capital: 'Сараево' },
  { code: 'hr', name: 'Хорватия', capital: 'Загреб' },
  { code: 'si', name: 'Словения', capital: 'Любляна' },
  { code: 'xk', name: 'Косово', capital: 'Приштина' },
  { code: 'dk', name: 'Дания', capital: 'Копенгаген' },
  { code: 'se', name: 'Швеция', capital: 'Стокгольм' },
  { code: 'no', name: 'Норвегия', capital: 'Осло' },
  { code: 'fi', name: 'Финляндия', capital: 'Хельсинки' },
  { code: 'is', name: 'Исландия', capital: 'Рейкьявик' },
  { code: 'ee', name: 'Эстония', capital: 'Таллин' },
  { code: 'lv', name: 'Латвия', capital: 'Рига' },
  { code: 'lt', name: 'Литва', capital: 'Вильнюс' },
  { code: 'ie', name: 'Ирландия', capital: 'Дублин' },
  { code: 'md', name: 'Молдова', capital: 'Кишинёв' },
  { code: 'cy', name: 'Кипр', capital: 'Никосия' },
  { code: 'mt', name: 'Мальта', capital: 'Валлетта' },
  { code: 'ad', name: 'Андорра', capital: 'Андорра-ла-Велья' },
  { code: 'sm', name: 'Сан-Марино', capital: 'Сан-Марино' },
  { code: 'mc', name: 'Монако', capital: 'Монако' },
  { code: 'li', name: 'Лихтенштейн', capital: 'Вадуц' },
  { code: 'va', name: 'Ватикан', capital: 'Ватикан' },

  // ── Азия ──────────────────────────────────────────────────────
  { code: 'kz', name: 'Казахстан', capital: 'Астана' },
  { code: 'uz', name: 'Узбекистан', capital: 'Ташкент' },
  { code: 'tm', name: 'Туркменистан', capital: 'Ашхабад' },
  { code: 'kg', name: 'Киргизия', capital: 'Бишкек' },
  { code: 'tj', name: 'Таджикистан', capital: 'Душанбе' },
  { code: 'ge', name: 'Грузия', capital: 'Тбилиси' },
  { code: 'am', name: 'Армения', capital: 'Ереван' },
  { code: 'az', name: 'Азербайджан', capital: 'Баку' },
  { code: 'tr', name: 'Турция', capital: 'Анкара' },
  { code: 'cn', name: 'Китай', capital: 'Пекин' },
  { code: 'jp', name: 'Япония', capital: 'Токио' },
  { code: 'kr', name: 'Южная Корея', capital: 'Сеул' },
  { code: 'kp', name: 'Северная Корея', capital: 'Пхеньян' },
  { code: 'mn', name: 'Монголия', capital: 'Улан-Батор' },
  { code: 'in', name: 'Индия', capital: 'Нью-Дели' },
  { code: 'pk', name: 'Пакистан', capital: 'Исламабад' },
  { code: 'bd', name: 'Бангладеш', capital: 'Дакка' },
  { code: 'lk', name: 'Шри-Ланка', capital: 'Коломбо' },
  { code: 'np', name: 'Непал', capital: 'Катманду' },
  { code: 'bt', name: 'Бутан', capital: 'Тхимпху' },
  { code: 'mv', name: 'Мальдивы', capital: 'Мале' },
  { code: 'af', name: 'Афганистан', capital: 'Кабул' },
  { code: 'ir', name: 'Иран', capital: 'Тегеран' },
  { code: 'iq', name: 'Ирак', capital: 'Багдад' },
  { code: 'sy', name: 'Сирия', capital: 'Дамаск' },
  { code: 'lb', name: 'Ливан', capital: 'Бейрут' },
  { code: 'il', name: 'Израиль', capital: 'Иерусалим' },
  { code: 'jo', name: 'Иордания', capital: 'Амман' },
  { code: 'sa', name: 'Саудовская Аравия', capital: 'Рияд' },
  { code: 'ye', name: 'Йемен', capital: 'Сана' },
  { code: 'om', name: 'Оман', capital: 'Маскат' },
  { code: 'ae', name: 'ОАЭ', capital: 'Абу-Даби' },
  { code: 'qa', name: 'Катар', capital: 'Доха' },
  { code: 'kw', name: 'Кувейт', capital: 'Кувейт' },
  { code: 'bh', name: 'Бахрейн', capital: 'Манама' },
  { code: 'th', name: 'Таиланд', capital: 'Бангкок' },
  { code: 'vn', name: 'Вьетнам', capital: 'Ханой' },
  { code: 'la', name: 'Лаос', capital: 'Вьентьян' },
  { code: 'kh', name: 'Камбоджа', capital: 'Пномпень' },
  { code: 'my', name: 'Малайзия', capital: 'Куала-Лумпур' },
  { code: 'sg', name: 'Сингапур', capital: 'Сингапур' },
  { code: 'id', name: 'Индонезия', capital: 'Джакарта' },
  { code: 'ph', name: 'Филиппины', capital: 'Манила' },
  { code: 'bn', name: 'Бруней', capital: 'Бандар-Сери-Бегаван' },
  { code: 'tl', name: 'Восточный Тимор', capital: 'Дили' },
  { code: 'mm', name: 'Мьянма', capital: 'Нейпьидо' },
  { code: 'tw', name: 'Тайвань', capital: 'Тайбэй' },
  { code: 'ps', name: 'Палестина', capital: 'Рамалла' },

  // ── Африка ────────────────────────────────────────────────────
  { code: 'eg', name: 'Египет', capital: 'Каир' },
  { code: 'ma', name: 'Марокко', capital: 'Рабат' },
  { code: 'dz', name: 'Алжир', capital: 'Алжир' },
  { code: 'tn', name: 'Тунис', capital: 'Тунис' },
  { code: 'ly', name: 'Либия', capital: 'Триполи' },
  { code: 'sd', name: 'Судан', capital: 'Хартум' },
  { code: 'ss', name: 'Южный Судан', capital: 'Джуба' },
  { code: 'et', name: 'Эфиопия', capital: 'Аддис-Абеба' },
  { code: 'er', name: 'Эритрея', capital: 'Асмэра' },
  { code: 'dj', name: 'Джибути', capital: 'Джибути' },
  { code: 'so', name: 'Сомали', capital: 'Могадишо' },
  { code: 'ke', name: 'Кения', capital: 'Найроби' },
  { code: 'ug', name: 'Уганда', capital: 'Кампала' },
  { code: 'tz', name: 'Танзания', capital: 'Додома' },
  { code: 'rw', name: 'Руанда', capital: 'Кигали' },
  { code: 'bi', name: 'Бурунди', capital: 'Гитега' },
  { code: 'cd', name: 'ДР Конго', capital: 'Киншаса' },
  { code: 'cg', name: 'Республика Конго', capital: 'Браззавиль' },
  { code: 'cf', name: 'ЦАР', capital: 'Банги' },
  { code: 'td', name: 'Чад', capital: 'Нджамена' },
  { code: 'cm', name: 'Камерун', capital: 'Яунде' },
  { code: 'gq', name: 'Экваториальная Гвинея', capital: 'Малабо' },
  { code: 'ga', name: 'Габон', capital: 'Либревиль' },
  { code: 'st', name: 'Сан-Томе и Принсипи', capital: 'Сан-Томе' },
  { code: 'ng', name: 'Нигерия', capital: 'Абуджа' },
  { code: 'ne', name: 'Нигер', capital: 'Ниамей' },
  { code: 'bf', name: 'Буркина-Фасо', capital: 'Уагадугу' },
  { code: 'ml', name: 'Мали', capital: 'Бамако' },
  { code: 'sn', name: 'Сенегал', capital: 'Дакар' },
  { code: 'gm', name: 'Гамбия', capital: 'Банжул' },
  { code: 'gw', name: 'Гвинея-Бисау', capital: 'Бисау' },
  { code: 'gn', name: 'Гвинея', capital: 'Конакри' },
  { code: 'sl', name: 'Сьерра-Леоне', capital: 'Фритаун' },
  { code: 'lr', name: 'Либерия', capital: 'Монровия' },
  { code: 'ci', name: 'Кот-д\'Ивуар', capital: 'Ямусукро' },
  { code: 'gh', name: 'Гана', capital: 'Аккра' },
  { code: 'tg', name: 'Того', capital: 'Ломе' },
  { code: 'bj', name: 'Бенин', capital: 'Порто-Ново' },
  { code: 'cv', name: 'Кабо-Верде', capital: 'Прая' },
  { code: 'mr', name: 'Мавритания', capital: 'Нуакшот' },
  { code: 'mw', name: 'Малави', capital: 'Лилонгве' },
  { code: 'zm', name: 'Замбия', capital: 'Лусака' },
  { code: 'zw', name: 'Зимбабве', capital: 'Хараре' },
  { code: 'mz', name: 'Мозамбик', capital: 'Мапуту' },
  { code: 'na', name: 'Намибия', capital: 'Виндхук' },
  { code: 'bw', name: 'Ботсвана', capital: 'Габороне' },
  { code: 'za', name: 'ЮАР', capital: 'Претория' },
  { code: 'ls', name: 'Лесото', capital: 'Масеру' },
  { code: 'sz', name: 'Эсватини', capital: 'Мбабане' },
  { code: 'mg', name: 'Мадагаскар', capital: 'Антананариву' },
  { code: 'mu', name: 'Маврикий', capital: 'Порт-Луи' },
  { code: 'sc', name: 'Сейшелы', capital: 'Виктория' },
  { code: 'km', name: 'Коморы', capital: 'Морони' },
  { code: 'ao', name: 'Ангола', capital: 'Луанда' },

  // ── Америка ───────────────────────────────────────────────────
  { code: 'us', name: 'США', capital: 'Вашингтон' },
  { code: 'ca', name: 'Канада', capital: 'Оттава' },
  { code: 'mx', name: 'Мексика', capital: 'Мехико' },
  { code: 'gt', name: 'Гватемала', capital: 'Гватемала' },
  { code: 'bz', name: 'Белиз', capital: 'Бельмопан' },
  { code: 'sv', name: 'Сальвадор', capital: 'Сан-Сальвадор' },
  { code: 'hn', name: 'Гондурас', capital: 'Тегусигальпа' },
  { code: 'ni', name: 'Никарагуа', capital: 'Манагуа' },
  { code: 'cr', name: 'Коста-Рика', capital: 'Сан-Хосе' },
  { code: 'pa', name: 'Панама', capital: 'Панама' },
  { code: 'cu', name: 'Куба', capital: 'Гавана' },
  { code: 'ht', name: 'Гаити', capital: 'Порт-о-Пренс' },
  { code: 'do', name: 'Доминиканская Республика', capital: 'Санто-Доминго' },
  { code: 'jm', name: 'Ямайка', capital: 'Кингстон' },
  { code: 'bs', name: 'Багамы', capital: 'Нассау' },
  { code: 'bb', name: 'Барбадос', capital: 'Бриджтаун' },
  { code: 'tt', name: 'Тринидад и Тобаго', capital: 'Порт-оф-Спейн' },
  { code: 'ag', name: 'Антигуа и Барбуда', capital: 'Сент-Джонс' },
  { code: 'dm', name: 'Доминика', capital: 'Розо' },
  { code: 'gd', name: 'Гренада', capital: 'Сент-Джорджес' },
  { code: 'kn', name: 'Сент-Китс и Невис', capital: 'Бастер' },
  { code: 'lc', name: 'Сент-Люсия', capital: 'Кастри' },
  { code: 'vc', name: 'Сент-Винсент и Гренадины', capital: 'Кингстаун' },
  { code: 'co', name: 'Колумбия', capital: 'Богота' },
  { code: 've', name: 'Венесуэла', capital: 'Каракас' },
  { code: 'gy', name: 'Гайана', capital: 'Джорджтаун' },
  { code: 'sr', name: 'Суринам', capital: 'Парамарибо' },
  { code: 'ec', name: 'Эквадор', capital: 'Кито' },
  { code: 'pe', name: 'Перу', capital: 'Лима' },
  { code: 'br', name: 'Бразилия', capital: 'Бразилиа' },
  { code: 'bo', name: 'Боливия', capital: 'Сукре' },
  { code: 'py', name: 'Парагвай', capital: 'Асунсьон' },
  { code: 'uy', name: 'Уругвай', capital: 'Монтевидео' },
  { code: 'ar', name: 'Аргентина', capital: 'Буэнос-Айрес' },
  { code: 'cl', name: 'Чили', capital: 'Сантьяго' },

  // ── Океания ───────────────────────────────────────────────────
  { code: 'au', name: 'Австралия', capital: 'Канберра' },
  { code: 'nz', name: 'Новая Зеландия', capital: 'Веллингтон' },
  { code: 'pg', name: 'Папуа — Новая Гвинея', capital: 'Порт-Морсби' },
  { code: 'fj', name: 'Фиджи', capital: 'Сува' },
  { code: 'sb', name: 'Соломоновы Острова', capital: 'Хониара' },
  { code: 'vu', name: 'Вануату', capital: 'Порт-Вила' },
  { code: 'ws', name: 'Самоа', capital: 'Апиа' },
  { code: 'to', name: 'Тонга', capital: 'Нукуалофа' },
  { code: 'tv', name: 'Тувалу', capital: 'Фунафути' },
  { code: 'ki', name: 'Кирибати', capital: 'Южная Тарава' },
  { code: 'nr', name: 'Науру', capital: 'Ярен' },
  { code: 'mh', name: 'Маршалловы Острова', capital: 'Маджуро' },
  { code: 'pw', name: 'Палау', capital: 'Нгерулмуд' },
  { code: 'fm', name: 'Микронезия', capital: 'Паликир' },
]
